version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        depends_on: 
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
            - '80:80'
    api:
        depends_on: 
            - postgres
            - redis
            - worker
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_moduless
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postres_password
            - PGPORT=5432
    client:
        depends_on: 
            - api
        stdin_open: true
        tty: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        depends_on: 
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
